"""
Django settings for Estudy_Project project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from pathlib import Path
import os
from pickle import FALSE
import sys

import environ


env = environ.Env()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = os.path.join(BASE_DIR, "templates")
STATIC_DIR = os.path.join(BASE_DIR, "static")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


DEFAULT_GRIDFS_URL = 'mongodb+srv://Estudy:5t4r3e2w1q@cluster0.yuqzy.mongodb.net/myFirstDatabase?retryWrites=true&w=majority' 

DEFAULT_GRIDFS_SERVE_URL = None  

DEFAULT_GRIDFS_COLLECTION = 'storage'

DEFAULT_FILE_STORAGE = 'gridfs_storage.storage.GridFSStorage'

UPLOADED_FILES_USE_URL = True


# SECRET_KEY = "django-insecure-$j+#%6nk5kuvsii6#je5#q!xwrb3e@)^-&9rmzd25$-edp1@fo"

SECRET_KEY = env(
    "DJANGO_SECRET_KEY",
    default="django-insecure-$j+#%6nk5kuvsii6#je5#q!xwrb3e@)^-&9rmzd25$-edp1@fo",
)

# SECRET_KEY = os.environ.get('SECRET_KEY', default='foo')


# SECURITY WARNING: don't run with debug turned on in production!

# DEBUG = True
# DEBUG = int(os.environ.get('DEBUG', default=0))
DEBUG = env.bool("DJANGO_DEBUG", FALSE)

CSRF_TRUSTED_ORIGINS = [
    'https://estudy-sce.herokuapp.com',
    'https://estudy1.herokuapp.com',
]


AUTH_USER_MODEL = "accounts.User"

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "estudy-sce.herokuapp.com",
    "estudy1.herokuapp.com",
]


# Application definition


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "HomePage",
    "DetailsAccount",
    "category",
    "phonenumber_field",
    "star_ratings",
    "forum",
    "captcha",
    "gridfs_storage",
    "YouTube",
]

X_FRAME_OPTIONS = "SAMEORIGIN"


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Estudy_Project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            TEMPLATES_DIR,
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Estudy_Project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

if "test" in sys.argv:
    DATABASES = {
        "default": {"ENGINE": "django.db.backends.sqlite3", "NAME": "mydatabase"}
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "djongo",
            "NAME": "Estudy",
            "CLIENT": {
                "host": "mongodb+srv://Estudy:5t4r3e2w1q@cluster0.yuqzy.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
]


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTION": {"min_length": 9},
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATIC_URL = "/static/"
STATICFILES_DIRS = [
    STATIC_DIR,
]
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


MEDIA_ROOT = BASE_DIR / "static/upload"
MEDIA_URL = "/upload/"

LOGIN_REDIRECT_URL = "HomePage:home"
LOGOUT_REDIRECT_URL = "HomePage:home"
EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
EMAIL_FILE_PATH = BASE_DIR / "sent_emails"
STAR_RATINGS_RERATE = True

# GOOGLE_API_KEY = "AIzaSyDBcuON7FOgCjoShKP8IdD3bCkUeXc-O3M"
RECAPTCHA_PUBLIC_KEY = "6Le5CJEfAAAAACuE9OLsAhzPb5rrNFGr4FZdlVf4"
RECAPTCHA_PRIVATE_KEY = "6Le5CJEfAAAAAFnHoQav2eiq0l8Dh5_foagL4UAL"


YOUTUBE_DATA_API_KEY = "AIzaSyB8y7m6JoevtDQai4vCH0VzTejuEy-EiSQ"




#mail service
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = 'estudy.sce@gmail.com'
SERVER_EMAIL = 'estudy.sce@gmail.com'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'estudy.sce@gmail.com'
EMAIL_HOST_PASSWORD = '5t4r3e2w1q'

